### PR TITLE
Hats-module integration

### PR DESCRIPTION
**Pull request by gershido**
- Refactor the existing implementation to inherit from HatsToggleModule
- Adjust the tests and deployment script

### CODE REVIEW

**Comment by spengrah** [comment]
looking good! Only thing I'd suggest adding is a comment in `SeasonToggle.sol` that references the immutables inherited from HatsModule. Here's [how I've been doing this](https://github.com/Hats-Protocol/hats-baal-shamans/blob/5e5dd13047b76a08e599fa079528aa1636fcd523/src/HatsOnboardingShaman.sol#L44) recently, for example.

**Comment by gershido** [comment]
I don't have access to the secrets, maybe there's a problem with the API tokens? Is it working for you?

**Comment by spengrah** [comment]
> I don't have access to the secrets, maybe there's a problem with the API tokens? Is it working for you?

@gershido I think its because of the secrets not being accessible from your personal repo. Here's what i see in the [actions logs](https://github.com/Hats-Protocol/season-toggle/actions/runs/5111013993/jobs/9187512750?pr=1#step:1:31) for this PR:

image

Compare with the [actions logs](https://github.com/Hats-Protocol/season-toggle/actions/runs/4855915404/jobs/9197971734#step:1:31) from the last commit to the main branch:

image

My suggestion is that you create a new branch in this repo with your changes, and then open a PR from that branch. My hypothesis is that the ci will work since it will have access to the secrets.

**Comment by gershido** [comment]
It worked! thanks. Now seems that there is a bug with "forge coverage" (internal bug), probably with handling re-mappings with dependencies. Found this reference:
https://github.com/foundry-rs/foundry/issues/2915

Tried to play around with the mappings and such but nothing works so far. If you don't have an idea for a quick fix, I think it's not worth spending time on this. I will open an issue on Foundry

**Comment by spengrah** [comment]
Yea I've run into that as well a bit, so I just gave up and turned off the coverage ci. Not ideal but also not the worst thing.

**Pull request merged**
